'use strict';
// Golden equivalence: every engine output over the corpus must match the pinned fixture byte for byte.
// Fixture generated by tests/fixtures/generar-golden.js from the pre-extraction engine (R3 step 1).
var test = require('node:test');
var assert = require('node:assert/strict');
var fs = require('fs');
var path = require('path');
var corpus = require('./fixtures/motor-corpus');
var api = require('./fixtures/motor-api').build();

var esperado = fs.readFileSync(path.join(__dirname, 'fixtures', 'motor-golden.json'), 'utf8');
var obtenido = corpus.canon(corpus.compute(api)) + '\n';
var A = JSON.parse(esperado), B = JSON.parse(obtenido);

test('golden: corpus covers the intended datasets', function(){
  assert.deepEqual(Object.keys(A.datasets), ['mixed2026', 'mixed2025', 'mixed2027', 'legacy2026', 'legacy2025', 'legacy2027', 'empty2026', 'emptyNull', 'emptyString']);
});

Object.keys(A.datasets).forEach(function(n){
  Object.keys(A.datasets[n]).forEach(function(campo){
    test('golden ' + n + ' / ' + campo, function(){ assert.deepEqual(B.datasets[n][campo], A.datasets[n][campo]); });
  });
});
Object.keys(A.pure).forEach(function(campo){
  test('golden pure / ' + campo, function(){ assert.deepEqual(B.pure[campo], A.pure[campo]); });
});

test('golden: the whole output is byte-identical to the fixture', function(){
  assert.equal(obtenido, esperado);
});
